sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: ITei8uO7UZH7jUDOi8xEf8KPPM6u5We1V8gqxtSjGBGWl0ZqqtaSh+wFVUP059fAlPyvUZRkh6gYqLFu/qBq9xuTpzH7F9nt2byhAvSWraPiXL1Y5uFSQprGOKB14FulfEJJlIJ/IaIV9JcDfD8yjsHhHigrcq/Zf4rs14wLVD8MBKsAL3FuZYIWwYJAVvqGvHD2v6rftr+m1d/+PWh3OmPeWCJBJC6UjQ4/aY7Z3aBXVHZeeTlS2SrZtL1goawHnjSQtC83nmzReRzzhmM5TCbtyMHfRXs894TIw30/2Cuzy9EwOczBZZ22P/pQklgPnOraCryZsmq++bY0ukEY6j0cP1mEKxPIJpcfV4fcsIl/OkAeWeAdaN82qcwQ875Vy1Nqd8bSATFkapgdM83axcc1xrduXlawYFQo6VPFNF/ZfUh0RGPyNzG4PxeFQWQErLqRreE1C7u7OtFmUM4LF2Cg/4o85z8wf0aUypdIytoR0O67pZg/FElGJsURJyxAXRpG10fohuUzvXDHhB/iFykGvXO8IykHe/NJgixqsLibhiTwr8gpx10Y6FEsYBLrrsxJzp7IY9sDHKJZUm4zwoM30TRg5zy/0tKHdPGZ9HyLLH1rLSU9IZmznpTldlgBv9+ixRKf//YYan1n0Ugpqwh2D2ZXZMxQ5HqkhQhEQsA=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Story-of-the-Treasure-Seekers--13-Being-the-Adventures-of-the-Bastable-Children-in-Search-o__770
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy